# release candidate pre-release
name: "release-rc"

on:
  push:
    branches:
      - "rc"
permissions: read-all

jobs:

  # ---------------------------------------------------------------------------
  build-with-clog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: check dependencies
        run:  bash ./clogrc/check.sh

      - name: build opentsg
        run:  bash ./clogrc/build.sh

      - name: opentsg-node-rc build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: opentsg-node-rc-build
          path: tmp/*-opentsg*
          retention-days: 7

  # ---------------------------------------------------------------------------
  pre-release-candidate:
    name: "Pre Release Candidate"
    runs-on: "ubuntu-latest"
    needs: build-with-clog

    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Release Candidate"
          files: tmp/*-opentsg*